/**
 * IMPORTANT: Loading glTF models into a Three.js scene is a lot of work.
 * Before we can configure or animate our model's meshes, we need to iterate through
 * each part of our model's meshes and save them separately.
 *
 * But luckily there is an app that turns gltf or glb files into jsx components
 * For this model, visit https://gltf.pmnd.rs/
 * And get the code. And then add the rest of the things.
 * YOU DON'T HAVE TO WRITE EVERYTHING FROM SCRATCH
 */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bird.glb -T --types
Author: NORBERTO-3D (https://sketchfab.com/norberto3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
Title: phoenix bird
*/

import { useRef, useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

interface BirdProps {
    position?: [number, number, number]
    rotation?: [number, number, number]
    scale?: [number, number, number] | number
}

// 3D Model from: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
export function Bird(props: BirdProps) {
    const group = useRef<THREE.Group>(null)
    
    // Load the 3D model and animations from the provided GLTF file
    const { scene, animations } = useGLTF('/assets/3d/transformed/bird-transformed.glb')
    
    // Clone the scene to avoid issues with multiple instances
    const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
    
    // Extract nodes and materials from the cloned scene
    const { nodes, materials } = useGraph(clone)
    
    // Get access to the animations for the bird
    useAnimations(animations, group)

    return (
        // Create a group to contain all bird mesh components
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                {/* Root joint for the bird skeleton */}
                <primitive object={nodes._rootJoint} />
                
                {/* Bird body parts - each skinned mesh represents a different part of the phoenix bird */}
                <skinnedMesh
                    name="Object_7"
                    geometry={(nodes.Object_7 as THREE.SkinnedMesh).geometry}
                    material={materials.MatI_Ride_FengHuang_01a}
                    skeleton={(nodes.Object_7 as THREE.SkinnedMesh).skeleton}
                    position={[-0.625, 0, -17.137]}
                    rotation={[0, 0.053, 0]}
                />
                <skinnedMesh
                    name="Object_8"
                    geometry={(nodes.Object_8 as THREE.SkinnedMesh).geometry}
                    material={materials.MatI_Ride_FengHuang_01b}
                    skeleton={(nodes.Object_8 as THREE.SkinnedMesh).skeleton}
                    position={[-0.625, 0, -17.137]}
                    rotation={[0, 0.053, 0]}
                />
            </group>
        </group>
    )
}

// Preload the bird model to improve performance
useGLTF.preload('/assets/3d/transformed/bird-transformed.glb')