/**
 * IMPORTANT: Loading glTF models into a Three.js scene is a lot of work.
 * Before we can configure or animate our model's meshes, we need to iterate through
 * each part of our model's meshes and save them separately.
 *
 * But luckily there is an app that turns gltf or glb files into jsx components
 * For this model, visit https://gltf.pmnd.rs/
 * And get the code. And then add the rest of the things.
 * YOU DON'T HAVE TO WRITE EVERYTHING FROM SCRATCH
 */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iceland_island.glb -T --types
Files: iceland_island.glb [35.34MB] > iceland_island-transformed.glb [2.11MB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import { type JSX } from 'react'
import * as THREE from 'three'

interface GLTFResult {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    model: THREE.Material
  }
}

/**
 * Renders a GLTF-based Iceland island mesh inside a root group.
 *
 * @param props - Props forwarded to the root <group> that contains the island mesh
 * @returns A React Three Fiber group element with the island mesh (geometry from `nodes.model` and material from `materials.model`)
 */
export function IcelandIsland(props: JSX.IntrinsicElements['group']) {
  // Load the 3D model from the provided GLTF file
  const { nodes, materials } = useGLTF('/assets/3d/transformed/iceland_island-transformed.glb') as unknown as GLTFResult
  
  return (
    // Create a group to contain the iceland island mesh
    <group {...props} dispose={null}>
      {/* Main iceland island model mesh */}
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  )
}

// Preload the iceland island model to improve performance
useGLTF.preload('/assets/3d/transformed/iceland_island-transformed.glb')