/**
 * IMPORTANT: Loading glTF models into a Three.js scene is a lot of work.
 * Before we can configure or animate our model's meshes, we need to iterate through
 * each part of our model's meshes and save them separately.
 *
 * But luckily there is an app that turns gltf or glb files into jsx components
 * For this model, visit https://gltf.pmnd.rs/
 * And get the code. And then add the rest of the things.
 * YOU DON'T HAVE TO WRITE EVERYTHING FROM SCRATCH
 */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 island_with_tower_v2.glb -T --types
Files: island_with_tower_v2.glb [40.51MB] > island_with_tower_v2-transformed.glb [2.35MB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import { useRef, useEffect } from 'react'
import { useFrame, useThree, type ThreeElement } from '@react-three/fiber'
import { a } from '@react-spring/three'
import { type JSX } from 'react'
import * as THREE from 'three'

interface IslandWithTowerProps {
  position?: [number, number, number]
  rotation?: [number, number, number]
  scale?: [number, number, number] 
  isRotating?: boolean
  setIsRotating?: (rotating: boolean) => void
  setCurrentStage?: (stage: number) => void
}

interface GLTFResult {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    model: THREE.Material
  }
}

// Island with Tower 3D model - enhanced version of fantasy island with tower structure
export function IslandWithTower(props: IslandWithTowerProps) {
  // Load the 3D model from the provided GLTF file
  const { nodes, materials } = useGLTF('/assets/3d/transformed/island_with_tower-transformed.glb') as unknown as GLTFResult
  
  return (
    // Create a group to contain the island with tower mesh
    <a.group {...props} dispose={null}>
      {/* Main island with tower  model mesh */}
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </a.group>
  )
}

// Preload the island with tower v2 model to improve performance
useGLTF.preload('/assets/3d/transformed/island_with_tower-transformed.glb')

export default IslandWithTower