/**
 * IMPORTANT: Loading glTF models into a Three.js scene is a lot of work.
 * Before we can configure or animate our model's meshes, we need to iterate through
 * each part of our model's meshes and save them separately.
 *
 * But luckily there is an app that turns gltf or glb files into jsx components
 * For this model, visit https://gltf.pmnd.rs/
 * And get the code. And then add the rest of the things.
 * YOU DON'T HAVE TO WRITE EVERYTHING FROM SCRATCH
 */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plane.glb -T --types
Author: AntijnvanderGun (https://sketchfab.com/AntijnvanderGun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-ww1-plane-c4edeb0e410f46e8a4db320879f0a1db
Title: Stylized WW1 Plane
*/

import { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

interface PlaneProps {
  isRotating?: boolean
  position?: [number, number, number]
  rotation?: [number, number, number]
  scale?: [number, number, number] | number
}

// 3D Model from: https://sketchfab.com/3d-models/stylized-ww1-plane-c4edeb0e410f46e8a4db320879f0a1db
export function Plane({ ...props }: PlaneProps) {
  const group = useRef<THREE.Group>(null)
  
  // Load the 3D model and its animations
  const { nodes, materials, animations } = useGLTF('/assets/3d/transformed/plane-transformed.glb')
  
  // Get animation actions associated with the plane
  useAnimations(animations, group)

  return (
    // Create a group to contain all plane mesh components
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.042}>
          {/* Simplified plane structure - keeping only main components */}
          <group name="polySurface172" position={[-0.825, 5.808, -1.092]} rotation={[0.013, 0.037, -0.065]}>
            {/* Propeller group */}
            <group name="polySurface171" position={[0, -0.57, 14.211]} rotation={[0, 0, -2.64]}>
              <group name="polySurface304" position={[0, -3.301, -12.838]}>
                <mesh 
                  name="polySurface304_pasted__lambert2_0" 
                  geometry={(nodes.polySurface304_pasted__lambert2_0 as THREE.Mesh)?.geometry} 
                  material={materials.pasted__lambert2} 
                />
              </group>
              <group name="polySurface406" position={[0, 0.007, -0.608]}>
                <mesh 
                  name="polySurface406_Tooner_0" 
                  geometry={(nodes.polySurface406_Tooner_0 as THREE.Mesh)?.geometry} 
                  material={materials.Tooner} 
                />
              </group>
            </group>
            
            {/* Propeller blades */}
            <group name="pCube1" position={[0, -0.57, 13.286]} rotation={[0, 0, 2.323]} scale={14.594}>
              <mesh 
                name="pCube1_Blur_effect_0" 
                geometry={(nodes.pCube1_Blur_effect_0 as THREE.Mesh)?.geometry} 
                material={materials.Blur_effect} 
              />
            </group>
            
            {/* Main fuselage body */}
            <group name="polySurface187" position={[0, -3.871, 1.373]}>
              <mesh 
                name="polySurface187_pasted__lambert2_0" 
                geometry={(nodes.polySurface187_pasted__lambert2_0 as THREE.Mesh)?.geometry} 
                material={materials.pasted__lambert2} 
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

// Preload the plane model to improve performance
useGLTF.preload('/assets/3d/transformed/plane-transformed.glb')