/**
 * IMPORTANT: Loading glTF models into a Three.js scene is a lot of work.
 * Before we can configure or animate our model's meshes, we need to iterate through
 * each part of our model's meshes and save them separately.
 *
 * But luckily there is an app that turns gltf or glb files into jsx components
 * For this model, visit https://gltf.pmnd.rs/
 * And get the code. And then add the rest of the things.
 * YOU DON'T HAVE TO WRITE EVERYTHING FROM SCRATCH
 */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 island_with_tower_v1.glb -T --types
Files: island_with_tower_v1.glb [7.62MB] > island_with_tower_v1-transformed.glb [407.41KB] (95%)
*/

import { useGLTF } from '@react-three/drei'
import { type JSX } from 'react'
import * as THREE from 'three'

interface GLTFResult {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    model: THREE.Material
  }
}

/**
 * Renders the "island with tower" GLTF model inside a Three.js group.
 *
 * Loads the model from '/assets/3d/transformed/island_with_tower_v1-transformed.glb' and mounts its primary mesh.
 *
 * @param props - Props forwarded to the root `<group>` element
 * @returns A JSX `<group>` containing the island-with-tower mesh
 */
export function Spaceship(props: JSX.IntrinsicElements['group']) {
  // Load the 3D model from the provided GLTF file
  const { nodes, materials } = useGLTF('/assets/3d/transformed/island_with_tower_v1-transformed.glb') as unknown as GLTFResult
  
  return (
    // Create a group to contain the island with tower mesh
    <group {...props} dispose={null}>
      {/* Main island with tower model mesh */}
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  )
}

// Preload the island with tower v1 model to improve performance
useGLTF.preload('/assets/3d/transformed/spaceship-transformed.glb')