/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/assets/3d/iceland_island.glb -T 
Files: /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/assets/3d/iceland_island.glb [35.34MB] > /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/models/iceland_island-transformed.glb [2.11MB] (94%)
*/

import { useGLTF } from '@react-three/drei'
import { type JSX } from 'react'
import * as THREE from 'three'

interface GLTFResult {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    model: THREE.Material
  }
}

export function IcelandIsland(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/iceland_island-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  )
}

useGLTF.preload('/iceland_island-transformed.glb')
