/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/assets/3d/island_with_tower_v1.glb -T 
Files: /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/assets/3d/island_with_tower_v1.glb [7.62MB] > /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/models/island_with_tower_v1-transformed.glb [407.41KB] (95%)
*/

import { useGLTF } from '@react-three/drei'
import { type JSX } from 'react'
import * as THREE from 'three'

interface GLTFResult {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    model: THREE.Material
  }
}

export function IslandWithTowerV1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/island_with_tower_v1-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.model.geometry} material={materials.model} />
    </group>
  )
}

useGLTF.preload('/island_with_tower_v1-transformed.glb')
