/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/assets/3d/sky.glb -T 
Files: /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/assets/3d/sky.glb [329.42KB] > /Users/caokaixiang/Downloads/3D_portfolio-main/my_project/src/models/sky-transformed.glb [35.48KB] (89%)
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-in-the-cloud-b270497defe24f9cb497b9a075eeb28f
Title: FREE - SkyBox In The Cloud
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sky-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={500} />
    </group>
  )
}

useGLTF.preload('/sky-transformed.glb')
